spring.application.name=Weather MCP Server

# MCP Server configuration
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=mcp-weather-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

server.port=8080

logging.level.dev.chiedo.weathermcpserver=DEBUG

